version: 2

jobs:
  build:
    docker:
      - image: benjamincharity/terminus-ui-ci:0.0.6

    working_directory: ~/ci-build

    environment:
      TEST_REPORTS: /coverage

    steps:
      - add_ssh_keys

      - checkout

      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Cache
          key: yarn
          paths:
            - ./node_modules

      # Will re-enable once linting is set up
      #- run:
          #name: Lint
          #command: yarn run lint:ci

      - run:
          name: Run Tests
          command: yarn run test:ci

      - store_test_results:
          path: coverage/junit/

      - run:
          name: Build Project
          command: yarn run build:ci

      - store_artifacts:
          path: coverage/
          destination: ~/coverage/

      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: ~/npm_logs/




# HACK: This will allow tags to kick off the deploy process. Correct syntax support is coming soon:
# https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
